server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  rabbitmq:
    host: centos7.jacktong726.com
    port: 5672
    username: guest
    password: guest
    virtualHost: /
  data:
    mongodb:
      uri:  mongodb://root:123456@centos7.jacktong726.com:27017
      database: xc_cms
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0