server:
  port: 31450
spring:
  application:
    name: xc-service-manage-media-processor
  data:
    mongodb:
      uri:  mongodb://root:123456@centos7.jacktong726.com:27017
      database: xc_media
#rabbitmq配置
  rabbitmq:
    host: centos7.jacktong726.com
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xc-service-manage-media:
  mq:
    routingkey-media-video: routingkey_media_video
    queue-media-video-processor: queue_media_video_processor
  video-location: F:/javalesson/javahw/xcedu/video/
  ffmpeg-path: F:/ffmpeg/bin/ffmpeg.exe