server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:123456@centos7.jacktong726.com:27017
      database: xc_cms
  rabbitmq:
    host: centos7.jacktong726.com
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    #queue: queue_cms_postpage_01
    queue: queue_cms_postpage_03
    #routingKey: 5a751fab6abb5044e0d19ea1 #此routingKey为门户站点ID
    routingKey: 5ee4f7e24176a33fa33a8fdc #此routingKey为課程發布站点ID